#pragma once
// -*- C++ -*-
//
// generated by wxGlade 1.0.5 on Mon Oct  7 10:02:54 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef KT_H
#define KT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class KT_Frame : public wxFrame {
public:
    // begin wxGlade: KT_Frame::ids
    // end wxGlade

    KT_Frame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: KT_Frame::attributes
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // KT_H